# Generated by Django 5.0 on 2023-12-16 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_product_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='phone_number',
            field=models.CharField(default=datetime.datetime(2023, 12, 16, 14, 16, 49, 982432, tzinfo=datetime.timezone.utc), max_length=15),
            preserve_default=False,
        ),
    ]
